# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "http", "~> 4.4"

gem "thor", "~> 1.0"

gem "dotenv", "~> 2.7"
